from django.db import models

# Create your models here.

STATES = (
    ('Alaska', 'Alaska'),
    ('Arizona', 'Arizona'),
    ('California', 'California'),
    ('Florida', 'Florida'),
    ('Georgia', 'Georgia'),
    ('Hawaii', 'Hawaii'),
    ('Maryland', 'Maryland'),
    ('Michigan', 'Michigan'),
    ('New Mexico', 'New Mexico'),
    ('Nevada', 'Nevada'),
    ('North Carolina', 'North Carolina'),
    ('Ohio', 'Ohio'),
    ('Pennsylvania', 'Pennsylvania'),
    ('South Carolina', 'South Carolina'),
    ('Tennessee', 'Tennessee'),
    ('Texas', 'Texas'),
    ('Utah', 'Utah'),
    ('Wisconsin', 'Wisconsin'),
   )

STATES_DICT = dict(STATES)

class Input(models.Model):

    state = models.CharField(max_length=50, choices=STATES)
    address = models.CharField(max_length=50)

SCHOOL_DISTRICTS = (
    ('Albuquerque Public Schools', 'Albuquerque Public Schools'),
    ('Aldine Independent School District', 'Aldine Independent School District'),
    ('Alpine School District', 'Alpine School District'),
    ('Anchorage School District', 'Anchorage School District'),
    ('Anne Arundel County Public Schools', 'Anne Arundel County Public Schools'),
    ('Arlington Independent School District', 'Arlington Independent School District'),
    ('Atlanta Public Schools', 'Atlanta public Schools'),
    ('Austin Independent School District', 'Austin Independent School District'),
    ('Baltimore City Public Schools', 'Baltimore City Public Schools'),
    ('Baltimore County Public Schools', 'Baltimore County Public Schools'),
    ('Brevard County School District', 'Brevard County School District'),
    ('Broward County School District', 'Broward County School District'),
    ('Brownsville Independent School District', 'Brownsville Independent School District'),
    ('South Carolina', 'South Carolina'),
    ('Capistrano Unified School District', 'Capistrano Unified School District'),
    ('Charlotte-Mecklenburg Schools', 'Charlotte-Mecklenburg Schools'),
    ('Clark County School District', 'Clark County School district'),
    ('Clayton County School District', 'Clayton County School District'),
    ('Cobb County School District', 'Cobb County School District'),
    ('Columbus City School District', 'Columbus City School District'),
    ('Conroe Independent School District', 'Conroe Independent School District'),
    ('Cumberland County Schools', 'Cumberland County Schools'),
    ('Cypress-Fairbanks Independent School District', 'Cypress-Fairbanks Independent School District'),
    ('Dallas Independent School District', 'Dallas Independent School District'),
    ('Dekalb County School District', 'Dekalb County School District'),
    ('Detroit City School District', 'Detroit City School District'),
    ('Duval County School District', 'Duval County School District'),
    ('El Paso Independent School District', 'El Paso Independent School District'),
    ('Elk Grove Unified School District', 'Elk Grove Unified School District'),
    ('Fort Bend Independent School District', 'Fort Bend Independent School District'),
    ('Fort Worth Independent School District', 'Fort Worth Independent School District'),
    ('Fresno Unified School District', 'Fresno Unified School District'),
    ('Fulton County School District', 'Fulton County School District'),
    ('Garden Grove Unified School District', 'Garden Grove Unified School District'),
    ('Garland Independent School District', 'Garland Independent School District'),
    ('Granite School District', 'Granite School District'),
    ('Greenville County School District', 'Greenville County School District'),
    ('Guilford County Schools', 'Guilford County Schools'),
    ('Gwinnett County School District', 'Gwinnett County School District'),
    ('Hawaii Department of Education', 'Hawaii Department of Education'),
    ('Hillsborough County School District', 'Hillsborough County School District'),
    ('Houston Independent School District', 'Houston Independent School District'),
    ('Howard County Public Schools', 'Howard County Public Schools'),
    ('Jordan School District', 'Jordan School District'),
    ('Katy Independent School District', 'Katy Independent School District'),
    ('Knox County School District', 'Knox County School District'),
    ('Lee County School District', 'Lee County School District'),
    ('Lewisville Independent School District', 'Lewisville Independent School District'),
    ('Long Beach Unified School District', 'Long Beach Unified School District'),
    ('Los Angeles Unified School District', 'Los Angeles Unified School District'),
    ('Mesa Unified School District', 'Mesa Unified School District'),
    ('Milwaukee School District', 'Milwaukee School District'),
    ('Montgomery County Public Schools', 'Montgomery County Public Schools'),
    ('North east Independent School District', 'North east Independent School District'),
    ('Orange County School District', 'Orange County School District'),
    ('Osceola County School District', 'Osceola County School District'),
    ('Palm beach County School District', 'Palm beach County School District'),
    ('Pasadena Independent School District', 'Pasadena Independent School District'),
    ('Philadelphia School District', 'Philadelphia School District'),
    ('Pinellas County School District', 'Pinellas County School District'),
    ('Plano Independent School District', 'Plano Independent School District'),
    ('Polk County School District', 'Polk County School District'),
    ('Prince George\'s County Public Schools', 'Prince George\'s County Public Schools'),
    ('Sacramento City Unified School District', 'Sacramento City Unified School District'),
    ('San Antonio Independent School District', 'San Antonio Independent School District'),
    ('San Bernardino City Unified School District', 'San Bernardino City Unified School District'),
    ('San Francisco Unified School District', 'San Francisco Unified School District'),
    ('San Juan Unified School District', 'San Juan Unified School District'),
    ('Santa Ana Unified School District', 'Santa Ana Unified School District'),
    ('Seminole County School District', 'Seminole County School District'),
    ('Shelby County School District', 'Shelby County School District'),
    ('Tucson Unified School District', 'Tucson Unified School District'),
    ('Volusia County School District', 'Volusia County School District'),
    ('Wake County Schools', 'Wake County Schools'),
    ('Washoe County School District', 'Washoe County School District'),
   )

SCHOOL_DISTRICTS_DICT = dict(SCHOOL_DISTRICTS)

class schools(models.Model):

    district = models.CharField(max_length=50, choices=SCHOOL_DISTRICTS)
